name: build and deploy to github pages

on:
  push:
    paths:
      - src/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - name: set up emsdk
        run: zig fetch --save=emsdk git+https://github.com/emscripten-core/emsdk#4.0.9
      - name: compile
        id: build
        run: zig build --release=fast -Dtarget=wasm32-emscripten
      - name: upload static files
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: zig-out/web
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4
