name: build and deploy to github pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  EM_VERSION: latest
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1
      - name: setup cache
        id: cache-system-libraries
        uses: actions/cache@v2
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - name: compile with emsdk
        id: build
        run: zig build -Dtarget=wasm32-emscripten --sysroot emsdk-cache/upstream/emscripten/
      - name: upload static files
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: zig-out/htmlout/
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4
